### ISSUE TITLE
Failed volume operation

### ISSUE THREAD

**Issue by zekeb** [Lurker00/Android-fs#1]
Thanks so much for this!  I really hope I can get it working.  I need a larger file size for a chroot Linux img.

I installed the .zip with CWM, and it succeeded.  I was getting no logfile in /data/local/tmp, so first I modified the install-recovery-2.sh to write the log to the /sdcard/.  Still no log, so I ran the install-recovery-2.sh script as SU in android terminal.  I got a report of success, and the SDcard error notification changed to preparing sdcard, but then it never appeared in the file manager, and in settings, the mount button for the external sdcard was greyed out.

I am using a Yoga tab 2 8" 830-F with Android 5.0.1. kernel 3.10.20-x86_64

Here is the log (note this was only generated when I ran the script from shell, not at boot):
'****** Fri Oct 16 02:07:44 CDT 2015 ******
id:  uid=0(root) gid=0(root) context=u:r:init:s0
Starting for /dev/block/mmcblk1p1
/dev/block/mmcblk1p1 file system: NTFS
/dev/block/mmcblk1p1 is NTFS
Mounting volume... OK
Processing of $MFT and $MFTMirr completed successfully.
Checking the alternate boot sector... OK
NTFS volume version is 3.1.
NTFS partition /dev/block/mmcblk1p1 was processed successfully.
/system/xbin/ntfs-3g -o rw,uid=1023,gid=1023,umask=0000,noatime /dev/block/mmcblk1p1 /mnt/media_rw/sdcard1
Using supolicy to provide permissions to fuse.
605 Volume sdcard1 /storage/sdcard1 state changed from 1 (Idle-Unmounted) to 3 (Checking)
605 Volume sdcard1 /storage/sdcard1 state changed from 3 (Checking) to 1 (Idle-Unmounted)
402 0 volume operation failed (No data available)
Mounted for fuse'

**Comment by zekeb** [comment]
EDIT:  Tried with an exFAT formatted card and had the same outcome. Same log entry

relevant entry from su - mount:
/dev/fuse /dev/sdcard1 fuse rw. nosuid, nodev, relatime, user_id=1023, groupid=1023, default_permissions, allow_other 0 0

**Comment by Lurker00** [comment]
I didn't upgrade to 5.0, and don't want to. I've already been reported that it does not work as expected under it. The reason is that the mount script (/system/etc/install-recovery-2.sh) is not launched at the system startup. But you can try manual launch from the terminal, as I wrote in the readme:
 
    su
    /system/etc/install-recovery-2.sh mount

where "mount" it just anything, but a required parameter to start from the terminal. I've been reported that it does work this way under Lollipop.

Regarding log files, if you create an empty file /data/local/tmp/exfat_mount.log, the mounting script will write the log into it. Of course, if the script is really launched. E.g.

    su
    cd /data/local/tmp
    touch exfat_mount.log
    chmod 666 exfat_mount.log

to be sure it is writeable.

**Comment by zekeb** [comment]
Thanks, I think the log not being written is related to the 5.0 problem you
mention - not launching install-recovery-2.sh at startup -  because it is
written when I call it from the terminal.

I never added the additional parameter when I launched the script manually
- maybe that was why it never finished the last task and froze ext-sd
access? Now I can't try it because in the process of trying to get
something better than FAT on my ext-SD, I borked the boot partition, so I
am bricked right now. (Any idea how to fix that? :) - I can't even get into
fastboot, just BIOS.

I'm still able to return this tablet, so I think I will.  I love the
design, screen, and battery life, but this tablet is just too locked down
to meet my needs.  New model is a non-starter.  Too bad, it had such
potential.

**Comment by OberonTSM** [comment]
Hello! I have the same issue as zekeb on Android 5. The log file has the same issue after the script is executed manually.
402 0 volume operation failed (No data available)
Mounted for fuse'
And no ability to use sdcard (Formatted as extFat). As far as I Understood, Android 5 has issue of mounting card at startup, but the manual execution of the script should proceed. But it doesn't (Nor NTFS Neither exFat). Could you help me?

**Comment by Lurker00** [comment]
No, I can't. I have no a device with Lollipop to investigate more.

**Comment by OberonTSM** [comment]
OK, Thank you. Maybe I'll switch the device back to KitKat.
